#!/bin/bash

# WolfServe Service Installer
# Installs WolfServe as a systemd service on Linux
#
# Usage: ./install_service.sh [-y|--yes]
#
# Environment variables (for non-interactive use):
#   WOLFSERVE_HOST         - Server bind address (default: 0.0.0.0)
#   WOLFSERVE_PORT         - Server port (default: 3000)
#   WOLFSERVE_FPM_PORT     - PHP-FPM port (default: 9993)
#   WOLFSERVE_SESSION_PATH - PHP session save path (default: /var/lib/php/sessions)
#   WOLFSERVE_APACHE_DIR   - Apache config directory (default: /etc/apache2 or /etc/httpd)

set -e

INSTALL_DIR="/opt/wolfserve"
SERVICE_NAME="wolfserve"

# Parse arguments
AUTO_YES=false
for arg in "$@"; do
    case $arg in
        -y|--yes)
            AUTO_YES=true
            shift
            ;;
    esac
done

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
  echo "❌ Please run as root (sudo ./install_service.sh)"
  exit 1
fi

echo "🐺 WolfServe Service Installer"
echo "=============================="
echo ""

# ============================================
# Configuration (interactive or from env vars)
# ============================================

# Detect default Apache directory
DEFAULT_APACHE_DIR="/etc/apache2"
if [ -d "/etc/httpd" ] && [ ! -d "/etc/apache2" ]; then
    DEFAULT_APACHE_DIR="/etc/httpd"
fi

# Set defaults from environment variables
SERVER_HOST="${WOLFSERVE_HOST:-0.0.0.0}"
SERVER_PORT="${WOLFSERVE_PORT:-3000}"
PHP_FPM_PORT="${WOLFSERVE_FPM_PORT:-9993}"
SESSION_SAVE_PATH="${WOLFSERVE_SESSION_PATH:-/var/lib/php/sessions}"
APACHE_CONFIG_DIR="${WOLFSERVE_APACHE_DIR:-$DEFAULT_APACHE_DIR}"

if [ "$AUTO_YES" = false ]; then
    echo "📝 Configuration Options (press Enter to accept defaults)"
    echo ""

    # Server settings
    read -p "Server bind address [$SERVER_HOST]: " INPUT
    SERVER_HOST="${INPUT:-$SERVER_HOST}"

    read -p "Server port [$SERVER_PORT]: " INPUT
    SERVER_PORT="${INPUT:-$SERVER_PORT}"

    # PHP settings
    read -p "PHP-FPM port [$PHP_FPM_PORT]: " INPUT
    PHP_FPM_PORT="${INPUT:-$PHP_FPM_PORT}"

    read -p "PHP session save path [$SESSION_SAVE_PATH]: " INPUT
    SESSION_SAVE_PATH="${INPUT:-$SESSION_SAVE_PATH}"

    # Apache settings
    read -p "Apache config directory [$APACHE_CONFIG_DIR]: " INPUT
    APACHE_CONFIG_DIR="${INPUT:-$APACHE_CONFIG_DIR}"
fi

echo ""
echo "📋 Configuration Summary:"
echo "   Server:       $SERVER_HOST:$SERVER_PORT"
echo "   PHP-FPM:      127.0.0.1:$PHP_FPM_PORT"
echo "   Sessions:     $SESSION_SAVE_PATH"
echo "   Apache dir:   $APACHE_CONFIG_DIR"
echo ""

if [ "$AUTO_YES" = false ]; then
    read -p "Proceed with installation? [Y/n]: " CONFIRM
    CONFIRM="${CONFIRM:-Y}"
    if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
        echo "Installation cancelled."
        exit 0
    fi
fi

echo ""
echo "🐺 Installing WolfServe as a service..."

# 1. Determine Web User
WEB_USER="www-data"
if id "apache" &>/dev/null; then
    WEB_USER="apache"
elif id "nginx" &>/dev/null; then
    WEB_USER="nginx"
elif id "http" &>/dev/null; then
    WEB_USER="http"
fi
if ! id "$WEB_USER" &>/dev/null; then
    echo "⚠️  Web user '$WEB_USER' not found. Creating system user 'wolfserve'..."
    useradd -r -s /bin/false wolfserve
    WEB_USER="wolfserve"
fi
echo "👤 Service will run as user: $WEB_USER"

# 2. Build Checks
if [ ! -f "target/release/wolfserve" ]; then
    echo "🔨 wolfserve binary not found. Building..."
    if command -v cargo &>/dev/null; then
        cargo build --release
    else 
        echo "❌ cargo not found. Please run ./install.sh first or install Rust."
        exit 1
    fi
fi

if [ ! -f "wolflib/target/release/libwolflib.so" ]; then
    echo "🔨 libwolflib.so not found. Building..."
    if [ -f "./build_lib.sh" ]; then
        sh ./build_lib.sh
    else
        cd wolflib && cargo build --release && cd ..
    fi
fi

# 3. Create Installation Directory
echo "📂 Creating install directory at $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
mkdir -p "$INSTALL_DIR/public"

# 4. Copy Files
echo "📦 Copying files..."
cp target/release/wolfserve "$INSTALL_DIR/"
cp wolflib/target/release/libwolflib.so "$INSTALL_DIR/"

# Generate config with user-specified options
echo "📝 Writing configuration to $INSTALL_DIR/wolfserve.toml..."
cat > "$INSTALL_DIR/wolfserve.toml" <<EOF
# WolfServe Configuration
# Generated by install_service.sh on $(date)

[server]
host = "$SERVER_HOST"
port = $SERVER_PORT

[php]
fpm_address = "127.0.0.1:$PHP_FPM_PORT"
mode = "fpm"
session_save_path = "$SESSION_SAVE_PATH"

[apache]
config_dir = "$APACHE_CONFIG_DIR"
EOF

# Copy public files
# Only copy if source public exists
if [ -d "public" ]; then
    cp -r public/* "$INSTALL_DIR/public/"
fi

# 5. Fix paths in public/rust.php if it exists
# We want to replace the hardcoded source path with the new install path
RUST_PHP="$INSTALL_DIR/public/rust.php"
if [ -f "$RUST_PHP" ]; then
    echo "🔧 Updating libwolflib.so path in $RUST_PHP..."
    # Escape slashes for sed
    ESCAPED_LIB_PATH=$(echo "$INSTALL_DIR/libwolflib.so" | sed 's/\//\\\//g')
    # Use generic regex to find $libPath = '...'; assignment
    sed -i "s/\$libPath = '.*';/\$libPath = '$ESCAPED_LIB_PATH';/" "$RUST_PHP"
fi

# Set permissions
chown -R $WEB_USER:$WEB_USER "$INSTALL_DIR"
chmod +x "$INSTALL_DIR/wolfserve"

# 6. Create Systemd Service
echo "⚙️  Creating systemd service /etc/systemd/system/$SERVICE_NAME.service..."
cat > /etc/systemd/system/$SERVICE_NAME.service <<EOF
[Unit]
Description=WolfServe High Performance Rust PHP Server
After=network.target php-fpm.service

[Service]
Type=simple
User=$WEB_USER
Group=$WEB_USER
WorkingDirectory=$INSTALL_DIR
ExecStart=$INSTALL_DIR/wolfserve
Restart=always
Environment=RUST_LOG=info
AmbientCapabilities=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
EOF

# 7. Configure PHP-FPM Pool
echo "🏊 Configuring PHP-FPM pool for WolfServe..."
FPM_POOL_CONF=""
# Attempt to find pool directory
if [ -d "/etc/php" ]; then
    # Debian/Ubuntu style: /etc/php/X.X/fpm/pool.d/
    # Find latest version
    PHP_VER=$(ls /etc/php/ | sort -V | tail -n1)
    if [ -d "/etc/php/$PHP_VER/fpm/pool.d" ]; then
        FPM_POOL_CONF="/etc/php/$PHP_VER/fpm/pool.d/wolfserve.conf"
    fi
elif [ -d "/etc/php-fpm.d" ]; then
    # RHEL/Fedora style
    FPM_POOL_CONF="/etc/php-fpm.d/wolfserve.conf"
fi

if [ -n "$FPM_POOL_CONF" ]; then
    echo "   Writing pool config to $FPM_POOL_CONF..."
    
    # Create session directory if needed
    if [ ! -d "$SESSION_SAVE_PATH" ]; then
        echo "   Creating session directory: $SESSION_SAVE_PATH"
        mkdir -p "$SESSION_SAVE_PATH"
    fi
    chown "$WEB_USER:$WEB_USER" "$SESSION_SAVE_PATH"
    chmod 1733 "$SESSION_SAVE_PATH"
    echo "   ✅ Session save path: $SESSION_SAVE_PATH"
    
    cat > "$FPM_POOL_CONF" <<EOF
[wolfserve]
user = $WEB_USER
group = $WEB_USER
listen = 127.0.0.1:$PHP_FPM_PORT
listen.owner = $WEB_USER
listen.group = $WEB_USER
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
php_admin_value[session.save_path] = $SESSION_SAVE_PATH
EOF
    echo "   ✅ PHP-FPM pool configured."
else
    echo "⚠️  Could not locate PHP-FPM pool directory. Please ensure PHP-FPM listens on 127.0.0.1:$PHP_FPM_PORT manually."
fi

# 8. Reload and Start
echo "🚀 Reloading daemons and starting services..."
systemctl daemon-reload

# Restart PHP-FPM to pick up new pool (handles both Fedora/RHEL and Debian/Ubuntu)
PHP_FPM_SVC=""
# Fedora/RHEL uses 'php-fpm', Debian/Ubuntu uses 'phpX.Y-fpm'
for svc in php-fpm php8.3-fpm php8.2-fpm php8.1-fpm php8.0-fpm php7.4-fpm; do
    if systemctl list-unit-files 2>/dev/null | grep -q "^$svc\.service"; then
        PHP_FPM_SVC="$svc"
        break
    fi
done
if [ -n "$PHP_FPM_SVC" ]; then
    echo "   Restarting $PHP_FPM_SVC..."
    systemctl enable "$PHP_FPM_SVC" 2>/dev/null || true
    systemctl restart "$PHP_FPM_SVC"
else
    echo "⚠️  Could not find PHP-FPM service. Please restart php-fpm manually."
fi

# Enable and start WolfServe
systemctl enable $SERVICE_NAME
systemctl restart $SERVICE_NAME

echo "✅ Installation complete!"
echo "   Server running on http://$(grep -m 1 'host =' $INSTALL_DIR/wolfserve.toml | cut -d '"' -f 2):$(grep -m 1 'port =' $INSTALL_DIR/wolfserve.toml | cut -d '=' -f 2 | tr -d ' ')"
echo "   Manage with: systemctl [start|stop|restart|status] $SERVICE_NAME"
echo ""
echo "⚠️  Don't forget to stop Apache and disable it if running on port 80/443:"
echo "   systemctl stop apache2 httpd"
echo "   systemctl disable apache2 httpd"
